### PR TITLE
API 500 Support for Logical Switch Group

### LINKED ISSUE #267: Support for Logical Switch Group - API500
### Scenario/Intent
Add support to Logical Switch Group on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource Logical Switch Group on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Adding Logical Switch Group for HPE OneView API500 support.

### Issues Resolved
#267 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: examples/logical_switch_group.rb [hunk 1]
```diff
@@ -9,10 +9,14 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
+# NOTE 1: This example requires two Scopes named "Scope1" and "Scope2" to be present in the appliance.
+# NOTE 2: The api_version client should be greater than 200 if you run the examples using Scopes
```
Comment (fgbulsoni) [inline examples/logical_switch_group.rb:13]: "greater than 200 if you run"   =>  "at least 300 to run"

File: spec/fixtures/cookbooks/oneview_test_api300_synergy/recipes/logical_switch_group_add_to_scopes.rb [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+# Unless required by applicable law or agreed to in writing, software distributed
+# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
+# CONDITIONS OF ANY KIND, either express or implied. See the License for the
+# specific language governing permissions and limitations under the License.
+#
+
+oneview_logical_switch_group 'LogicalSwitchGroup1' do
+  client node['oneview_test']['client']
+  api_version 300
+  api_variant 'C7000'
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api300_synergy/recipes/logical_switch_group_add_to_scopes.rb:20]: /oneview_test_api300_**synergy**/recipes/logical_switch_group_add_to_scopes.rb
api_variant **'C7000'**

Not particularly important, but sort of a mismatch between playbook and api_variant being used

**Review by fgbulsoni — APPROVED** [review]
Minor comments/suggestions. The PR looks good though. :octocat:

**Review by tmiotto — APPROVED** [review]
👀
