### PR TITLE
API500 Support for Enclosure

### LINKED ISSUE #301: Support for Enclosure - API500
### Scenario/Intent
Add support toEnclosure on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource Enclosure on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
- Added API500 support to oneview_enclosure.
- Added actions to add, remove or replace scopes for oneview_enclosure.

### Issues Resolved
#301 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: resources/enclosure.rb [hunk 1]
```diff
@@ -16,6 +16,9 @@
 property :refresh_state, String, default: 'RefreshPending'
 property :options, Hash, default: {}
 
+# API300 or greater
```
Comment (fgbulsoni) [inline resources/enclosure.rb]: I'd drop the comment and leave the property together with the other ones, or use an in-line comment.

**Review by fgbulsoni — APPROVED** [review]
Small comment, PR looks good :octocat:
