### PR TITLE
Storage System support to API500

### LINKED ISSUE #304: Add refresh actions to oneview_storage_system
### Scenario/Intent
Simply call the action :refresh in oneview_storage_system on APIs 200 and 300.

### Environment Details
 - **oneview Cookbook Version:** 2.3.0

### Steps to Reproduce
Look at the code.

### Expected Result
Storage System should have resfresh action

### Actual Result
Storage System does not have refresh actions.

### PR DESCRIPTION
**Pull request by tmiotto**
### Description
Adds support to refresh in previous versions of Storage System
Adds support to Storage System in API500:
 - Changes refresh  behavior in API500
 - Adds unit test cookbook for API500
 - Adds new example showing StoreServ storage system

### Issues Resolved
Fixes #304

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb [hunk 1]
```diff
@@ -0,0 +1,7 @@
+name             'oneview_test_api500_synergy'
+maintainer       'none'
+license          'All rights reserved'
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:3]: Shouldn't this be `license 'Apache v2.0'?

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+description      'A test cookbook for the oneview cookbook API500::Synergy module'
+version          '0.1.0'
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:5]: Shouldn't it be '1.0.0' ? Any point starting it on 0.1.0?

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb [hunk 3]
```diff
@@ -0,0 +1,7 @@
+name             'oneview_test_api500_synergy'
+maintainer       'none'
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:2]: Perhaps this should be listed as `Hewlett Packard Enterprise`? As this is maintained by us at the moment.
The description of the field does imply that would be correct "The name of the person responsible for maintaining a cookbook, either an individual **or an organization.**"

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/recipes/storage_system_refresh.rb [hunk 4]
```diff
@@ -0,0 +1,20 @@
+#
+# Cookbook Name:: oneview_test_api500_synergy
+# Recipe:: storage_system_refresh
+#
+# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api500_synergy/recipes/storage_system_refresh.rb]: 2017?

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/attributes/default.rb [hunk 5]
```diff
@@ -0,0 +1,20 @@
+#
+# Cookbook Name:: oneview_test_api300_synergy
+# Attributes:: default
+#
+# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test_api500_synergy/attributes/default.rb]: 2017?

File: spec/fixtures/cookbooks/oneview_test/recipes/storage_system_refresh.rb [hunk 6]
```diff
@@ -0,0 +1,20 @@
+#
+# Cookbook Name:: oneview_test
+# Recipe:: storage_system_refresh
+#
+# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (fgbulsoni) [inline spec/fixtures/cookbooks/oneview_test/recipes/storage_system_refresh.rb]: 2017?

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
A few comments, looking pretty good overall

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb (hunk 2 above)
Comment (tmiotto) [reply spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:5]: This is the fake cookbook for testing

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb (hunk 1 above)
Comment (tmiotto) [reply spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:3]: It is a fake testing cookbook, it's a fixture

File: spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb (hunk 3 above)
Comment (tmiotto) [reply spec/fixtures/cookbooks/oneview_test_api500_synergy/metadata.rb:2]: It doesn't matter, it is a fake testing cookbook, it doesn't even works

**Review by ricardogpsf — APPROVED** [review]
After make requested changes of @fgbulsoni, this PR is good for me.

**Review by fgbulsoni — APPROVED** [review]
