### PR TITLE
Fixed the wrong methods called inside the storage pool provider

### LINKED ISSUE #340: Storage pool actions for API 500 are not working
### Scenario/Intent
Running examples of StoragePool for API500 (examples/storage_pool_store_serv.rb), the actions of api500 (update, add_to_management, remove_from_management and refresh) throw errors, because some methods called by Oneview resource instance are not correct.

It is occuring 3 problems:

 1 - StoragePoolProvider of API500 is calling the `set_storage_system` method of OneviewSDK::API500::C7000::StoragePool through an instance of StoragePool, but method is not present in StoragePool of api500. This error occurs always when StorageSystem is loaded and the StorageSystem should be loaded for all actions.

 2 - StoragePoolProvider of API500 is calling the `manage` method of OneviewSDK::API500::C7000::StoragePool through an instance of StoragePool using a string as parameter, but the method expect a boolean parameter, so always when `add_to_management` and `remove_from_management` actions are called, the error is thrown. 
 
3 - The refresh action should load the StorageSystem before apply the action, otherwise the StoragePool is not found, but the refresh action is not loading the StorageSystem before. =(

For API200 and API300 all it is ok.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Issues Resolved
#340 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb [hunk 1]
```diff
@@ -18,20 +18,19 @@ module C7000
       class StoragePoolProvider < API300::C7000::StoragePoolProvider
         include OneviewCookbook::RefreshActions::RequestRefresh
 
+        def refresh
+          load_storage_system
+          super
+        end
+
         def load_storage_system
           raise("Unspecified property: 'storage_system'. Please set it before attempting this action.") unless @new_resource.storage_system
```
Comment (fgbulsoni) [inline libraries/resource_providers/api500/c7000/storage_pool_provider.rb]:
```ruby
validate_required_properties(:storage_system)
```
(?)

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb [hunk 2]
```diff
@@ -62,7 +61,7 @@ def update
           load_storage_system
           desired_state = Marshal.load(Marshal.dump(@item.data))
           @item.retrieve! || raise("Resource not found: The #{@resource_name} '#{@name}' could not be found")
-          update_manage_state(desired_state['isManaged'])
+          update_manage_state(desired_state['isManaged']) if desired_state['isManaged']
```
Comment (aalexmonteiro) [inline libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: If  ```desired_state ['isManaged']``` was false, this will never run, so I can never change to unmanaged.

Comment (ricardogpsf) [reply libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: Very good, Sorry for this mistake. The correct is `unless desired_state['isManaged'].nil?`
😄

Comment (ricardogpsf) [reply libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: I think that this line is not necessary, because the action to change the management occurs with the update of StoragePool, so even with this wrong if clause, we are changing the management to true or false, always .
But maybe this line was put there with some reason, I believe that is for maintain convergence of Chef applying convergence to the status of the StoragePool management. So I will maintain that line and fix the if clause.

File: CHANGELOG.md [hunk 3]
```diff
@@ -54,6 +54,7 @@ Bug fixes:
 - [#287](https://github.com/HewlettPackard/oneview-chef/issues/287) Disable FrozenString magic comment cop from Rubocop until the support is done
 - [#243](https://github.com/HewlettPackard/oneview-chef/issues/243) Chef-client 13.2.20 does not allow modification of property :save_resource_info
 - [#180](https://github.com/HewlettPackard/oneview-chef/issues/180) Create Mixins for the resource providers common methods
+- [#340](https://github.com/HewlettPackard/oneview-chef/issues/340) Storage Pool provider for api500 is not working well
```
Comment (aalexmonteiro) [inline CHANGELOG.md]: The name of the issue was changed to ```Storage pool actions for API 500 are not working```. Please, change to current name.

**Review by aalexmonteiro — APPROVED** [review]

**Review by fgbulsoni — APPROVED** [review]
LGTM

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb [hunk 4]
```diff
@@ -18,20 +18,19 @@ module C7000
...
+          @item['storageSystemUri'] = load_resource(:StorageSystem, { hostname: @new_resource.storage_system, name: @new_resource.storage_system }, :uri)
         end
 
         def update_manage_state(managed)
-          status = 'managed'
-          status = 'unmanaged' unless managed
-          return Chef::Log.info("#{@resource_name} '#{@name}' is already #{status}") if @item['isManaged'] == managed
-          @context.converge_by "#{@resource_name} '#{@name}' is now #{status}" do
+          return Chef::Log.info("#{@resource_name} '#{@name}' managed status is already #{managed}") if @item['isManaged'] == managed
+          @context.converge_by "#{@resource_name} '#{@name}' managed status is now #{managed}" do
```
Comment (tmiotto) [inline libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: This message does not makes much sense "_Potato Potato_ **managed status is now false**"

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb [hunk 5]
```diff
@@ -18,20 +18,19 @@ module C7000
...
+        end
+
         def load_storage_system
           raise("Unspecified property: 'storage_system'. Please set it before attempting this action.") unless @new_resource.storage_system
-          data = {
-            hostname: @new_resource.storage_system,
-            name: @new_resource.storage_system
-          }
-          @item.set_storage_system(load_resource(:StorageSystem, data))
+          @item['storageSystemUri'] = load_resource(:StorageSystem, { hostname: @new_resource.storage_system, name: @new_resource.storage_system }, :uri)
```
Comment (tmiotto) [inline libraries/resource_providers/api500/c7000/storage_pool_provider.rb:28]: Why did you remove the helper method?

**Review by tmiotto — CHANGES_REQUESTED** [review]

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb (hunk 5 above)
Comment (ricardogpsf) [reply libraries/resource_providers/api500/c7000/storage_pool_provider.rb:28]: This helper method is not found to resource of API500, it is present only to API200 and API300.

Comment (tmiotto) [reply libraries/resource_providers/api500/c7000/storage_pool_provider.rb:28]: Well, it should be there in the API500 in oneview-sdk.

Please open an issue there and one here to change this later.

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb [hunk 6]
```diff
@@ -29,8 +29,9 @@ def load_storage_system
         end
 
         def update_manage_state(managed)
-          return Chef::Log.info("#{@resource_name} '#{@name}' managed status is already #{managed}") if @item['isManaged'] == managed
-          @context.converge_by "#{@resource_name} '#{@name}' managed status is now #{managed}" do
+          managedText = managed ? 'managed' : 'unmanaged'
```
Comment (tmiotto) [inline libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: please use `snake_case`

**Review by tmiotto — CHANGES_REQUESTED** [review]

File: libraries/resource_providers/api500/c7000/storage_pool_provider.rb (hunk 6 above)
Comment (ricardogpsf) [reply libraries/resource_providers/api500/c7000/storage_pool_provider.rb]: oh God, Sorry! haha 😅

**Review by tmiotto — APPROVED** [review]

**Review by tmiotto — APPROVED** [review]
excellent 🐍
