### PR TITLE
API 500 Support for Logical Interconnect Group

### LINKED ISSUE #278: Support for Logical Interconnect Group - API500
### Scenario/Intent
Add support to Logical Interconnect Group on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **OneView API Version:** 500
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource Logical Interconnect Group on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
API 500 Support for Logical Interconnect Group.

### Issues Resolved
#278   

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: examples/logical_interconnect_group.rb [hunk 1]
```diff
@@ -12,12 +12,15 @@
 # NOTE: This recipe requires:
 # Ethernet Networks: EthernetNetwork1, EthernetNetwork2
 # FC Network: FCNetwork1
+# Scopes: Scope1, Scope2
 
+# NOTE: The api_version client should be greater than 200 if you run the examples using Scopes
```
Comment (fgbulsoni) [inline examples/logical_interconnect_group.rb]: I'd swap `greater than 200` for `(...) 300 or greater (...)`. Since 200 is not supported, it probably makes sense to not even mention it.

**Review by tmiotto — APPROVED** [review]
🍰 ✨

**Review by fgbulsoni — APPROVED** [review]
The PR overall looks good, but one thing I'm wondering:
Most of the resources that gained the add/remove/replace scopes will have tests that are basically the same as these, right? 
Perhaps it is worth creating a `shared` base for these, which will only be included by the resources and then each one could pass in its type through a `let` for instance?
This is not a *must*, but I do imagine that the resources which will gain those actions will have tests that are pretty similar

**Comment by ricardogpsf** [comment]
> The PR overall looks good, but one thing I'm wondering:
Most of the resources that gained the add/remove/replace scopes will have tests that are basically the same as these, right?
Perhaps it is worth creating a shared base for these, which will only be included by the resources and then each one could pass in its type through a let for instance?
This is not a must, but I do imagine that the resources which will gain those actions will have tests that are pretty similar

@fgbulsoni yes, it is good idea. =) 
We can do that in another PR, what do you think?

**Comment by tmiotto** [comment]
> We can do that in another PR, what do you think?

Issue it, PR it, We review it, merge it, Done.

**Comment by fgbulsoni** [comment]
> Issue it, PR it, We review it, merge it, Done.

Also, doing this sooner than later will mean less effort spent repeating tests. Doing it later will just mean reworking the tests for not a whole lot of gain.

**Comment by ricardogpsf** [comment]
Issue #306 registered.
