### PR TITLE
Helper Methods, Examples & Yard

### LINKED ISSUE #137: Change support references to mention API version instead of OneView version
### Scenario/Intent
Update doc references from OV version to match API version.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0

### Steps to Reproduce
Go through documentation ( README.md, CHANGELOG.md, and templates/ )

### Expected Result
All support references should mention the API version

### Actual Result
Some support references should mention the OneView version

### LINKED ISSUE #228: Make ResourceProvider #load_resource a helper method
### Scenario/Intent
Use the `#load_resource` method outside a ResourceProvider instance.
This will be helpful for users writing custom Ruby code in recipes, libraries, etc.
We can do something similar to how we handled the `#get_diff` and `#convert_keys` methods in ResourceProvider, where we just wrap the Helper method.
My goal is to make it easy for people to write simple, safe custom code

### Environment Details
 - **oneview Cookbook Version:** 2.2.0

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
This PR is a bit of a hodge-podge, so sorry. It:
- Moves the logic of the `load_resource` method into the Helper module, making it accessible outside Provider instances
- Updates a few examples & docs to be more consistent & accurate
- Adds an example of how make custom `ruby_block` resources
- Adds a yard config file and badge to the README. This will be great for Provider classes

### Issues Resolved
Fixes #228 
Fixes #137

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: libraries/oneview_helper.rb [hunk 1]
```diff
@@ -192,6 +192,37 @@ def self.recursive_diff(data, desired_data, str = '', indent = '')
...
+    # @return [OneviewSDK::Resource] if the `ret_attribute` is nil
+    # @return [String, Array, Hash] that is, the value of the resource attribute defined by `ret_attribute`
+    # @raise [OneviewSDK::NotFound] ResourceNotFound if the resource cannot be found
+    # @raise [OneviewSDK::IncompleteResource] If you don't specify any unique identifiers in `id`
+    def self.load_resource(client, type: nil, id: nil, ret_attribute: nil, api_ver: nil, variant: nil, node: nil, base_module: OneviewSDK)
+      raise(ArgumentError, 'Must specify a resource type') unless type
+      return unless id
+      c = build_client(client)
+      api_ver ||= node ? node['oneview']['api_version'] : 200
+      variant ||= node ? node['oneview']['api_variant'] : 'C7000'
```
Comment (tmiotto) [inline libraries/oneview_helper.rb]: I suggest:
```ruby
api_ver ||= node['oneview']['api_version'] rescue 200
variant ||= node['oneview']['api_variant'] rescue 'C7000'
```

**Review by tmiotto — APPROVED** [review]
:taco: :shipit:
