### PR TITLE
API 500 Support for Switch

### LINKED ISSUE #270: Support for Switch - API500
### Scenario/Intent
Add support to Switch on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource Switch on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Adding Switch for HPE OneView API500 support.

### Issues Resolved
#270 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [x] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: examples/switch.rb [hunk 1]
```diff
@@ -23,14 +27,33 @@
   client my_client
```
Comment (tmiotto) [inline examples/switch.rb:26]: You've added new actions, please change the comment above to be more realistic.

File: examples/switch.rb [hunk 2]
```diff
@@ -20,9 +20,10 @@
 }
 
 # Example: No action is executed.
-# In a resource that has only one action and no action is specified in the block
-# Chef executes this one. To prevent Chef from removing a switch as the standard action we created
-# the none action
+# In a resource that only has a remove action and other actions without great relevance to be considered
+# a standard action and no action is specified in the block Chef executes this one.
```
Comment (tmiotto) [inline examples/switch.rb]: I can't understand what you've said there, but I guess it should be:
> In a resource that only has destructive and non intuitive actions, Chef executes the none action to avoid mistakes.

**Review by tmiotto — APPROVED** [review]
