### PR TITLE
API 500 Support for ID Pool

### LINKED ISSUE #260: Support for ID Pool - API500
### Scenario/Intent
Add support to ID Pool on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource ID Pool on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Adding ID Pool for HPE OneView API500 support.

### Issues Resolved
#260 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: examples/id_pool.rb [hunk 1]
```diff
@@ -18,38 +18,38 @@
...
+oneview_id_pool 'VMAC Pool 4' do
   client my_client
   pool_type 'vmac'
   count 2
   action :allocate_count
 end
 
 # Example: Removing a list of the IDs
-oneview_id_pool 'VMAC Pool' do
+oneview_id_pool 'VMAC Pool 5' do
```
Comment (tmiotto) [inline examples/id_pool.rb]: Why the every example is executed in a different ID Pool? Use only the necessary resources.

**Review by tmiotto — APPROVED** [review]
🍃 ✨
