### PR TITLE
API 500 Support for Unmanaged Device

### LINKED ISSUE #262: Support for Unmanaged Device - API500
### Scenario/Intent
Add support to Unmanaged Device on the API500.

### Environment Details
 - **oneview Cookbook:** Version: 2.3.0
 - **OneView Version:** 3.10
 - **chef-client Version:** 12.0+
 - **platform:** Any

### Steps to Reproduce
Try to use the resource Unmanaged Device on the API 500.

### Expected Result
This resource supports API 500.

### Actual Result
This resource does not support API 500.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Adding Unmanaged Device for HPE OneView API500 support.

### Issues Resolved
#262 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
  - [] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [x] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: examples/unmanaged_device.rb [hunk 1]
```diff
@@ -25,7 +25,8 @@
 end
 
 # Example: Removes an unmanaged device
-oneview_unmanaged_device 'UnmanagedDevice1' do
+oneview_unmanaged_device 'UnmanagedDevice2' do
```
Comment (fgbulsoni) [inline examples/unmanaged_device.rb]: I'm guessing these changes make no sense.

**Review by fgbulsoni — CHANGES_REQUESTED** [review]
Not really a lot going on, looks fine but I'd definitely fix the example file.

**Review by fgbulsoni — APPROVED** [review]
