### PR TITLE
Fixes oneview_server_profile custom_attributes interactions

### LINKED ISSUE #234: Server Profile does not fill default values for OS Custom Attributes automatically
### Scenario/Intent
If some attribute that does have a default value is not passed in the osDeploymentSettings' osCustomAttributes, it appears as not set in OneView instead assuming its default value.

### Environment Details
 - **oneview Cookbook Version:** 2.2.1
 - **OneView Version:** API300

### Steps to Reproduce
1. Try to apply a server profile with a valid os_deployment_plan with custom attributes that have default values.
2. Do not define these default value attributes in the OS custom attributes inside 'data' => 'osDeploymentSettings' => 'osCustomAttributes'.

#### Expected Result
The attributes that weren't specified should appear with default values, if they have. 

#### Actual Result
The attributes that weren't specified appears as Not Set, even if they have default values.

### Root cause analysis
OneView does not sets these values, we need to perform a get then a override only the ones specified by the user in the osCustomAttributes before using the SDK's set_os_deployment_settings.

### PR DESCRIPTION
**Pull request by tmiotto**
### Description
Fixes oneview_server_profile custom_attributes interactions:
 - It supports both 'osCustomAttributes' and 'customAttributes' keys
 - It gathers the default values for the deployment plan custom attributes automatically
 - The warning message when both custom_attributes and data['osDeploymentSettings']['osCustomAtrributes'] are defined is now fixed and working.

Updates the gem dependency:
 - Bumps up minimum `oneview-sdk` requirement to 4.5.1 (It has a critical fix that is needed in this code)
 - Fixes `bekshelf` version to ~> 5.6.5 since the 6.0.0 version is already published

### Issues Resolved
#234 
#232 
#240

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
  - [ ] New resources and/or actions have are included in the [matchers.rb](https://github.com/HewlettPackard/oneview-chef/blob/master/libraries/matchers.rb) and [matchers_spec](https://github.com/HewlettPackard/oneview-chef/blob/master/spec/unit/resources/matchers_spec.rb).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in [examples](https://github.com/HewlettPackard/oneview-chef/tree/master/examples/) (please include helpful comments).
- [ ] Changes documented in the [CHANGELOG](https://github.com/HewlettPackard/oneview-chef/blob/master/CHANGELOG.md).

### CODE REVIEW

File: libraries/resource_providers/api300/synergy/server_profile_provider.rb [hunk 1]
```diff
@@ -29,13 +29,39 @@ def load_os_deployment_plan
...
+          customs ||= []
+          customs.each do |ca|
+            custom_replace!(defaults, ca)
+          end
+          defaults.select { |da| da['value'] }.collect { |ca| { 'name' => ca['name'], 'value' => ca['value'] } }
+        end
+
+        def custom_replace!(target, custom_attribute)
+          was_replaced = false
+          target.collect! do |da|
```
Comment (fgbulsoni) [inline libraries/resource_providers/api300/synergy/server_profile_provider.rb]: Perhaps use `default_attribute` instead of `da` here

**Review by fgbulsoni — COMMENTED** [review]
Slight adjustment to name of var suggested. Other than that, PR looks solid. :octocat:

**Review by fgbulsoni — APPROVED** [review]
Leaving approval since requested change is minor. ✨

File: libraries/resource_providers/api300/synergy/server_profile_provider.rb [hunk 2]
```diff
@@ -45,20 +45,23 @@ def load_os_deployment_plan
...
           defaults ||= []
           customs ||= []
-          customs.each do |ca|
-            custom_replace!(defaults, ca)
+          customs.each do |custom_attribute|
+            custom_replace!(defaults, custom_attribute)
           end
-          defaults.select { |da| da['value'] }.collect { |ca| { 'name' => ca['name'], 'value' => ca['value'] } }
+          # At this point, the defaults contain the custom data plus the default attributes
+          # It selects all the ones that has 'value', i.e. custom attributes or actual default attributes that have a default 'value'
```
Comment (fgbulsoni) [inline libraries/resource_providers/api300/synergy/server_profile_provider.rb]: (...)all the ones that have a 'value'
